# list of participants, names and email addresses

- :name:  "Frasier Crane"
  :email: "frasier.crane@kacl.talkradio.com"
- :name:  "Marty Crane"
  :email: "martycrane1946@compuserve.com"
- :name:  "Ronee Lawrence-Crane"
  :email: "roneelawrence64@aol.com"
- :name:  "Niles Crane"
  :email: "niles.crane@cranetherapist.com"
- :name:  "Daphne Crane"
  :email: "daphne.moon@freeserve.co.uk"
- :name:  "Maris Crane"
  :email: "flybynight@mauricescybercafe.aw"
- :name:  "Lilith Sternin"
  :email: "lilith.sternin@sterninassociates.net"
- :name:  "Freddy Crane"
  :email: "lilgoth88@hotmail.com"
- :name:  "Roz Doyle"
  :email: "roz.doyle@kacl.talkradio.com"
